spring:
  application:
    name: lockbench
  profiles:
    group:
      mysql-redis:
        - mysql
        - mysql-redis
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

lockbench:
  redis-lock:
    enabled: false
  thread-fixed:
    platform-concurrency: 200
    virtual-concurrency: 200
  run-store:
    max-size: 500
